### ISSUE TITLE
As an admin, I would like to be able to remove a restaurant from the database so the program can always have relevant and up to date information

### ISSUE THREAD

**Issue by mcorrente1** [xavierliancw/Fast-Food-Project#2]
Overview:
- Admin is able to remove a restaurant through the GUI
- Admin menu will have an remove restaurant button
- The button will be grayed out unless a restaurant is highlighted
- Clicking the button will delete the restaurant

Definition of Done:
- [x] The updated database looks like the restaurant was never there to begin with
- [x] The program can read the updated database without any hiccups
- [x] After pressing the confirm button the database is updated
- [x] The cancel button returns to the previous screen

How to Test:
- [x] Check if the deletion works
- [x] Check if database is empty
- [x] Check that database is still intact

**Comment by xavierliancw** [comment]
There is actually a bug with this where the distances don't get updated properly.
