### ISSUE TITLE
MasterStructure::loadFile(QString fileName) doesn't read distances in properly

### ISSUE THREAD

**Issue by xavierliancw** [xavierliancw/Fast-Food-Project#22]
- All of Saddleback's distances to every other restaurant is 8
- Distance from 3 to 4 is incorrect. It should be 4.3, but 11.5 is what the program thinks.
- Perhaps a redesign of distance handling is required...

**Comment by mcorrente1** [comment]
Refactored the code and issue should be fixed.  Can someone confirm the fix then close this issue out?
