### ISSUE TITLE
Persistence Bug where Sonic and Pizza Hut stay after deletion and restart.

### ISSUE THREAD

**Issue by xavierliancw** [xavierliancw/Fast-Food-Project#30]
I encountered a bug while testing.
When I imported Sonic and Pizza Hut, and tried deleting them, they stay in the .txt file.

They stay even after a program save and restart, so...

**Comment by mcorrente1** [comment]
this is fixed. all restaurants can successfully be deleted (issue with distances being updated after restaurant deletion is not fixed in this fix)
